/*
 * CalendarP.java
 *
 * Created on 19 mars 2003, 16:00
 */

package basepackage;
import java.util.Hashtable  ; import java.util.Date  ;import java.util.Vector  ;
import javax.swing.* ;import  java.text.SimpleDateFormat   ;
import java.util.Enumeration  ; import  java.text.ParseException   ;
/**
 *
 * @author  dd
 */
public class CalendarP extends javax.swing.JPanel {
public  Date  lastD   ; //dernier  jour de cotations 
    public Vector periodlist   , intervallist;  
 public Vector monthL  ;    // public Hashtable monthH  ;
   public DefaultComboBoxModel dvm1 , dvm11  ,dvm2 , dvm22  , dvm3 , dvm33  , dcm1 ; 
    public boolean today   = true  ;
   /** Creates new form CalendarP */
    public CalendarP() {
        initComponents();
    }
    
    public void init (   ) {
  initDayCombo (  ) ; initMonthCombo (  ) ;  initYearCombo (  ) ; //initIntervalCombo (  );
    }
    
   public void setUniqueDate(   )   {
jComboBox11.setEnabled(    false   )   ;  jComboBox2.setEnabled(    false   )   ; jComboBox21.setEnabled(    false   )   ;      
  }
    
   
    
    public void initDayCombo (  ) {  //pour le choix d'une date d'intraday
dvm1 =  new  DefaultComboBoxModel (  ) ;   //dvm11 =  new  DefaultComboBoxModel (  ) ;
for ( int s =1 ;s<32 ;s++  ) { 
    dvm1.addElement ( new Integer (s )  )  ;
 }
 this.jComboBox21.setModel( dvm1  ) ; 
  }
       
    public void initMonthCombo (  ) {
dvm2 =  new  DefaultComboBoxModel (  ) ;
for ( int s =1 ;s<13 ;s++  ) {
    dvm2.addElement ( new Integer (s )  )  ;
 }
 this.jComboBox11.setModel ( dvm2 ) ;
 
  }
          
          public void initYearCombo (  )  {
 dvm33 =  new  DefaultComboBoxModel (  ) ;        
for ( int  h= 2000 ;h<2010 ;h++  ) {  
     dvm33.addElement ( new Integer( h )  )  ; 
}    
   this.jComboBox2.setModel ( dvm33 ) ;  
}

      public Date getFixedDate  (  )   {  //on prend    la date de  FRom
   int year1  =  getYear(   ) ;   int mth1 = getMonth (    )  ; int dy1  = getDay (  ) ;  //tjs le decalage d'1 mois '
String date1S  = transformDate (  dy1  , mth1  , year1  , null     ) ;System.out.println (  "date1S :"+date1S )   ;
Date dt1 = getDateValue (  date1S  , "ddMMyy"      ) ;
return dt1 ;
   }

       public static Date getDateValue( String text  , String pattern   )  {
        SimpleDateFormat dft  =   new    SimpleDateFormat(pattern) ;
        try {
            return    dft.parse( text  )   ;
        } catch ( ParseException ep  )  {System.out.println( ep )  ; return null  ;}
    }


        public static String transformDate(  int dy   ,  int  my ,  int  year  ,String yearS  ) {  // year ss forme  02  , ou  95 vef que les strings sont bien au frmat ddMMyy
        String val =""  ;
        if( dy < 10 )  {  val +=0+""+dy  ;} else  {  val +=dy  ;}
        if( my < 10 )  {  val +=0+""+my  ;} else  {  val +=my  ;}
        if( year  !=-1  ) {
            yearS  = ""+year;
            val +=yearS.substring( 2)  ; //substring (  2  ,  4  )
        }else  { val +=yearS  ;   }
        return val  ;
    }


   public int getYear (     ) {
    Integer it  ;
    it  =(Integer)jComboBox2.getSelectedItem (   ) ;
    return  it.intValue (    ) ;
 }

 public int getMonth (  ) {
 Integer it  ;
    it  =(Integer)jComboBox11.getSelectedItem (   ) ;
    return  it.intValue (    ) ;
 }

 public int getDay (  ) {
  Integer it   ;
     it  =(Integer)jComboBox21.getSelectedItem (   ) ;
    return  it.intValue (    ) ;
    }

          
    public void  initComboModel (  String  [] tab  ,  DefaultComboBoxModel dcm  ) {
   for ( int s =0  ;s<tab.length;s++  ) {
 dcm.addElement (  tab[s]  ) ;      
   }
  }
      

    
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jPanel41 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel411 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(500, 72));
        setPreferredSize(new java.awt.Dimension(500, 72));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(500, 24));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 24));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel31.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mois");
        jPanel31.add(jLabel1, new java.awt.GridBagConstraints());
        jPanel31.add(jComboBox11, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel31, new java.awt.GridBagConstraints());

        jPanel41.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Year");
        jPanel41.add(jLabel2);
        jPanel41.add(jComboBox2);

        jPanel2.add(jPanel41, new java.awt.GridBagConstraints());

        jPanel411.setLayout(new java.awt.GridLayout(1, 2));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Day");
        jPanel411.add(jLabel21);
        jPanel411.add(jComboBox21);

        jPanel2.add(jPanel411, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jPanel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Today");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
  if(  jCheckBox1.isSelected()  )   {
     today    = true   ;
  }else  {    today  =  false    ;}  
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel411;
    // End of variables declaration//GEN-END:variables
    
}
