/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectionMotif.java
 *
 * Created on Apr 29, 2010, 3:06:33 AM
 */

package basepackage;
import  javax.swing.DefaultListModel    ; import  java.util.Vector    ;
import  javax.swing.JButton    ;   import    java.awt.event.*     ;       
/*
 *
 * @author root
 */
public class SelectionMotif extends javax.swing.JDialog {
public ListRendering  rendererL     ;public CPEUtility   cpu    ;public AbsenceMotif selectA    ;  public DefaultListModel  dlm   ;
public Vector  motifL    ;
    /** Creates new form SelectionMotif */
    public SelectionMotif(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    public void init(  )  {
dlm     =  new DefaultListModel(  )   ;   jList1.setCellRenderer(   rendererL  );
  cpu.addList( motifL  ,  dlm  , ConstantFolder.motifabsence    )     ;
  jList1.setModel(  dlm   );
  JButton   closeB  ,   selectB    =   new  JButton(     )    ;
  selectB.setText(   "Selectionner") ;
  jPanel1.add(   selectB     )   ;
         selectB.addActionListener( new ActionListener()
           {
               public void actionPerformed(ActionEvent e)
               {
                  selectMotif(     )  ; 
               }
           }
       );
  
  
  closeB   =   new  JButton(     )    ;
  closeB.setText(   "Annuler") ;
   closeB.addActionListener( new ActionListener()
           {
               public void actionPerformed(ActionEvent e)
               {
                 setVisible( false    )   ; 
               }
           }
       );
  
  jPanel1.add(   closeB       )   ;
  //+  une innner class 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public void  selectMotif(   )    {
        ListObj  lbj  =(ListObj)jList1.getSelectedValue()     ;
selectA    =(AbsenceMotif)lbj.value      ;
setVisible(    false  )     ;
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectionMotif dialog = new SelectionMotif(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
